version: '3.8'

services:
  database:
#    container_name: database
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always # always restart unless stopped manually
#    environment:
#      MYSQL_ROOT_PASSWORD: symfony
#      MYSQL_DATABASE: symfony
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: symfony
#    ports:
#      - '4306:3306'
#    volumes:
     container_name: warehouse_db
     image: mariadb:10.8.3
     command: --default-authentication-plugin=mysql_native_password
     restart: always # always restart unless stopped manually
     environment:
      MYSQL_ROOT_PASSWORD: root
     ports:
        - '4307:3306'
     volumes:
        - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9009:8080

  php:
    container_name: warehouse_php
    build:
      context: ./php
    ports:
      - '9001:9001'
    volumes:
      - ./app:/var/www

  nginx:
    container_name: warehouse_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
